#!/bin/bash

CRATE_NAME=$(cargo get -n) 

cargo build --release --target wasm32-unknown-unknown

wasm-bindgen --out-dir wasm/target --target web target/wasm32-unknown-unknown/release/${CRATE_NAME}.wasm

basic-http-server wasm
